### ISSUE TITLE
AttributeError: planet4

### ISSUE THREAD

**Issue by mschwamb** [michaelaye/p4tools#1]
* Planet Four Tools version:  0.8.0 a
* Python version: 3.6.2 
* Operating System: macOS Mojave

### Description
following the steps from the readme I get this error 
>>> from p4tools import io
No configuration file /Users/mschwamb/.p4tools.ini found.

Please provide the path where you want to store planet4 meta-data:/Users/mschwamb/Research/planetfour/p4tools_tmpdir
Saved database path into /Users/mschwamb/.p4tools.ini.
>>> fans = io.get_fan_catalog()
Downloading catalog
Traceback (most recent call last):
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/intake/catalog/base.py", line 330, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/intake/catalog/base.py", line 401, in __getitem__
    raise KeyError(key)
KeyError: 'planet4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/p4tools/io.py", line 136, in get_fan_catalog
    return get_intake_p4_item("fans", update)
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/p4tools/io.py", line 124, in get_intake_p4_item
    df = getattr(intake.cat.planet4, item_name).read()
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/intake/catalog/base.py", line 332, in __getattr__
    raise AttributeError(item)
AttributeError: planet4
>>> fans = io.get_fan_catalog()
Downloading catalog
Traceback (most recent call last):
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/intake/catalog/base.py", line 330, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/intake/catalog/base.py", line 401, in __getitem__
    raise KeyError(key)
KeyError: 'planet4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/p4tools/io.py", line 136, in get_fan_catalog
    return get_intake_p4_item("fans", update)
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/p4tools/io.py", line 124, in get_intake_p4_item
    df = getattr(intake.cat.planet4, item_name).read()
  File "/Users/mschwamb/anaconda/envs/p36/lib/python3.6/site-packages/intake/catalog/base.py", line 332, in __getattr__
    raise AttributeError(item)
AttributeError: planet4

**Comment by michaelaye** [comment]
oh, could it be that you did not install the catalog? Otherwise I'm not sure why the `planet4` key would be missing in the `intake` catalog?
Got to do `conda install -c michaelaye planetfour-catalog` before using `p4tools`.

**Comment by mschwamb** [comment]
Weirdly getting this issue

 conda install -c michaelaye planetfour-catalog 
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - planetfour-catalog -> intake

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/michaelaye/osx-64
  - https://conda.anaconda.org/michaelaye/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

I'm using python 3.6

**Comment by michaelaye** [comment]
I cannot reproduce with a fresh 3.6 conda environment. Could be an old conda version? I'm using 4.7.11. If you have anything smaller than conda 4.6, there were quite some bugs in the dependency resolver.

**Comment by michaelaye** [comment]
I see that your search folders are quite old, so i bet that's the conda version. The error is caused by not finding the `intake` package, but that's available in a channel called `pkgs/main` now which your conda doesn't seem to know about. But installing it from `conda-forge` should also work:

`conda install -c conda-forge intake`

However, you should really update conda, as it's much faster since 4.7.x.

Here's my search results for `intake`:
```
$ conda search -c conda-forge intake
Loading channels: done
# Name                       Version           Build  Channel
intake                         0.2.9            py_0  conda-forge
intake                         0.3.0          py37_0  pkgs/main
intake                         0.3.0            py_0  conda-forge
intake                         0.4.1          py36_0  pkgs/main
intake                         0.4.1          py37_0  pkgs/main
intake                         0.4.1            py_0  conda-forge
intake                         0.4.2            py_0  conda-forge
intake                         0.4.2            py_0  pkgs/main
intake                         0.4.3            py_0  conda-forge
intake                         0.4.4            py_0  conda-forge
intake                         0.4.4            py_0  pkgs/main
intake                         0.5.0            py_0  conda-forge
intake                         0.5.1            py_0  conda-forge
intake                         0.5.1            py_0  pkgs/main
intake                         0.5.2            py_0  conda-forge
intake                         0.5.3            py_0  conda-forge
intake                         0.5.3            py_0  pkgs/main
```

**Comment by mschwamb** [comment]
and I thought I've been updating conda and anaconda all the time. I've gotten something to update but it now says custom version which is a bit scary but it resolved the error...

**Comment by michaelaye** [comment]
are you using the Anaconda Navigator GUI? If so,  I can't help much, I only know it's not as reliable as only using the terminal. If you came from a conda 4.5, I might even consider reinstalling the whole she-bang, too many changes happened to 4.7, and I don't like to have uncleaned software skeletons lying around. Thanks to the speed-up it isn't too painful. Also have a look at my conda talk that explains the differences between ana/mini/conda https://www.dropbox.com/s/ezz1d8gy1s0dmu2/conda_talk.pdf?dl=0

**Comment by mschwamb** [comment]
I was using the terminal.
